# This file is generated by Codex, since it has no core RL logic inside.

import argparse
from pathlib import Path
import socket
import threading
import webbrowser

import torch
import torch.nn.functional as F
from flask import Flask, redirect, render_template_string, request, url_for

from config import BOARD_SIZE, UI_ITER, CURRENT_MODELS_DIR, USE_MCTS_UI
from mcts import MCTS
from model import PolicyNetwork
from utils import check_win_cond, get_policy_state, step


DEFAULT_MODEL_PATH = CURRENT_MODELS_DIR / f"final_policy_{UI_ITER}.pt"
MCTS_UI_SIMS = 200
MAX_UNDO_MOVES = 5


def make_game_state(
    board,
    message,
    game_over,
    player_color,
    next_turn,
    last_action,
    analysis=None,
    mcts=None,
    undo_stack=None,
):
    return {
        "board": board,
        "message": message,
        "game_over": game_over,
        "player_color": player_color,
        "next_turn": next_turn,
        "last_action": last_action,
        "analysis": analysis,
        "mcts": mcts,
        "undo_stack": undo_stack or [],
    }


def get_device():
    if torch.backends.mps.is_available():
        return torch.device("mps")
    return torch.device("cpu")


def empty_board(device=None):
    if device is None:
        device = get_device()
    return torch.zeros((2, BOARD_SIZE, BOARD_SIZE), dtype=torch.float32, device=device)


def load_policy(path, device=None):
    if device is None:
        device = get_device()
    policy = PolicyNetwork().to(device)
    checkpoint = torch.load(Path(path), map_location=device)
    state_dict = checkpoint["model"] if "model" in checkpoint else checkpoint
    policy.load_state_dict(state_dict)
    policy.eval()
    return policy


def board_to_symbols(state):
    occupied = state[0] + 2 * state[1]
    cells = []
    for row_idx in range(BOARD_SIZE):
        row = []
        for col_idx in range(BOARD_SIZE):
            cell = int(occupied[row_idx][col_idx].item())
            if cell == 1:
                row.append("B")
            elif cell == 2:
                row.append("W")
            else:
                row.append("")
        cells.append(row)
    return cells


def select_policy_action(policy, state, policy_turn):
    if check_win_cond(state, 1 - policy_turn, -1) == 2:
        return None

    policy_state = get_policy_state(state, policy_turn)

    with torch.no_grad():
        action_logits, value = policy(policy_state.unsqueeze(0))
        action_logits = action_logits.squeeze(0)
        occupied_spaces = state.sum(dim=0)
        legal_mask = (occupied_spaces == 0).flatten()
        masked_logits = action_logits.masked_fill(~legal_mask, float("-inf"))
        action_probs = F.softmax(masked_logits, dim=-1)
        action_dist = torch.distributions.Categorical(probs=action_probs)
        return int(action_dist.sample().item())


def create_mcts(policy, state, policy_turn, last_action):
    return MCTS(
        state=state,
        whose_turn=policy_turn,
        last_action=last_action,
        policy=policy,
        total_sim_for_one_move=MCTS_UI_SIMS,
    )


def analyze_policy_state(
    policy,
    state,
    policy_turn,
    top_k=3,
    last_action=-1,
    use_mcts=False,
    mcts=None,
    mcts_policy=None,
):
    if check_win_cond(state, 1 - policy_turn, -1) == 2:
        return [], 0.0, None

    policy_state = get_policy_state(state, policy_turn)

    with torch.no_grad():
        action_logits, value = policy(policy_state.unsqueeze(0))
        action_logits = action_logits.squeeze(0)
        value = float(value.squeeze().item())
        occupied_spaces = state.sum(dim=0)
        legal_mask = (occupied_spaces == 0).flatten()

        masked_logits = action_logits.masked_fill(~legal_mask, float("-inf"))
        action_probs = F.softmax(masked_logits, dim=-1)
        legal_count = int(legal_mask.sum().item())
        _, top_actions = torch.topk(action_probs, k=min(top_k, legal_count))
        sorted_actions = top_actions.tolist()
        selected_action = None
        mcts_stats = {}
        if use_mcts:
            if mcts is None:
                mcts = create_mcts(mcts_policy or policy, state, policy_turn, last_action)
            selected_action, _, mcts_stats = mcts.select_action(return_stats=True)
            sorted_actions = sorted(
                mcts_stats,
                key=lambda action: (mcts_stats[action]["N"], float(action_probs[action].item())),
                reverse=True,
            )[:top_k]

    ranked_moves = []
    for action in sorted_actions:
        prob = float(action_probs[action].item())
        stats = mcts_stats.get(action, {})
        ranked_moves.append({
            "action": action,
            "row": action // BOARD_SIZE,
            "col": action % BOARD_SIZE,
            "prob": prob,
            "prob_pct": round(prob * 100),
            "mcts_count": stats.get("N"),
            "q": stats.get("Q"),
            "p": stats.get("P"),
            "exploration": stats.get("exploration"),
            "prior_boost": stats.get("prior_boost"),
        })
    return ranked_moves, value, selected_action


def evaluate_outcome(state, last_player, action):
    winner = check_win_cond(state, last_player, action)
    if winner == 0:
        return "Black wins."
    if winner == 1:
        return "White wins."
    if winner == 2:
        return "Draw."
    return None


def parse_int_form_value(name):
    try:
        return int(request.form[name])
    except (KeyError, TypeError, ValueError):
        return None


def make_undo_snapshot(game_state):
    return {
        "board": game_state["board"].clone(),
        "message": game_state["message"],
        "game_over": game_state["game_over"],
        "player_color": game_state["player_color"],
        "next_turn": game_state["next_turn"],
        "last_action": game_state["last_action"],
        "analysis": game_state["analysis"],
    }


def push_undo_snapshot(game_state):
    undo_stack = list(game_state.get("undo_stack") or [])
    undo_stack.append(make_undo_snapshot(game_state))
    return undo_stack[-MAX_UNDO_MOVES:]


def restore_undo_snapshot(snapshot, undo_stack, message):
    return make_game_state(
        board=snapshot["board"].clone(),
        message=message,
        game_over=snapshot["game_over"],
        player_color=snapshot["player_color"],
        next_turn=snapshot["next_turn"],
        last_action=snapshot["last_action"],
        analysis=snapshot["analysis"],
        mcts=None,
        undo_stack=undo_stack,
    )


def can_undo_player_move(game_state):
    player_color = game_state["player_color"]
    if not game_state.get("undo_stack") or player_color is None:
        return False
    return True


def initialize_game_state(policy, mcts_policy, device, player_color):
    board = empty_board(device=device)
    if player_color == 0:
        return make_game_state(
            board=board,
            message="New game. You are Black and move first.",
            game_over=False,
            player_color=0,
            next_turn=0,
            last_action=-1,
        )

    mcts = create_mcts(mcts_policy, board, policy_turn=0, last_action=-1) if USE_MCTS_UI else None
    moves, value, selected_action = analyze_policy_state(
        policy,
        board,
        policy_turn=0,
        top_k=3,
        last_action=-1,
        use_mcts=USE_MCTS_UI,
        mcts=mcts,
        mcts_policy=mcts_policy,
    )
    if not moves:
        return make_game_state(
            board=board,
            message="Draw.",
            game_over=True,
            player_color=1,
            next_turn=None,
            last_action=-1,
        )

    return make_game_state(
        board=board,
        message="New game. You are White. The policy is about to open as Black.",
        game_over=False,
        player_color=1,
        next_turn=0,
        last_action=-1,
        analysis={
            "moves": moves,
            "value": value,
            "selected_action": selected_action,
        },
        mcts=mcts,
    )


def create_app(model_path=DEFAULT_MODEL_PATH):
    app = Flask(__name__)
    app.config["MODEL_PATH"] = Path(model_path)
    app.config["DEVICE"] = get_device()
    app.config["POLICY"] = load_policy(app.config["MODEL_PATH"], app.config["DEVICE"])
    if USE_MCTS_UI and app.config["DEVICE"].type != "cpu":
        app.config["MCTS_POLICY"] = load_policy(app.config["MODEL_PATH"], torch.device("cpu"))
    else:
        app.config["MCTS_POLICY"] = app.config["POLICY"]
    app.config["GAME_STATE"] = make_game_state(
        board=empty_board(device=app.config["DEVICE"]),
        message="Choose whether to play Black or White to start a new game.",
        game_over=True,
        player_color=None,
        next_turn=None,
        last_action=-1,
    )

    template = """
    <!doctype html>
    <html lang="en">
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>Gomoku vs Policy</title>
      <style>
        :root {
          color-scheme: light;
          --bg: #efe2c4;
          --bg-deep: #d6b983;
          --panel: rgba(255, 249, 236, 0.82);
          --surface: rgba(255, 252, 243, 0.86);
          --board: #c89d62;
          --board-line: rgba(70, 45, 20, 0.48);
          --text: #24170d;
          --accent: #7a3e1d;
          --accent-dark: #5d2f17;
          --stone-black: #1f1d1b;
          --stone-white: #fbf7ef;
          --shadow: rgba(64, 34, 15, 0.18);
        }
        html,
        body {
          height: 100%;
          overflow: hidden;
        }
        body {
          margin: 0;
          height: 100vh;
          height: 100dvh;
          font-family: Georgia, "Times New Roman", serif;
          background: #efe2c4;
          color: var(--text);
        }
        main {
          max-width: 1120px;
          margin: 0 auto;
          height: 100dvh;
          box-sizing: border-box;
          display: flex;
          flex-direction: column;
          justify-content: flex-start;
          padding: clamp(6px, 1.5vh, 14px) clamp(8px, 2vw, 16px);
        }
        .panel {
          background: var(--panel);
          border: 1px solid rgba(102, 66, 32, 0.18);
          border-radius: 20px;
          padding: clamp(8px, 1.5vh, 14px);
          box-shadow: 0 12px 26px var(--shadow);
          backdrop-filter: blur(10px);
          display: flex;
          flex-direction: column;
          align-items: stretch;
          flex: 1 1 auto;
          min-height: 0;
          overflow: hidden;
        }
        .status-area {
          display: grid;
          grid-template-columns: auto minmax(0, 1fr);
          gap: 8px;
          margin-bottom: clamp(6px, 1.3vh, 10px);
          flex: 0 0 auto;
          align-items: stretch;
        }
        .toolbar {
          display: flex;
          flex-wrap: wrap;
          justify-content: flex-start;
          align-items: center;
          gap: 6px;
          min-height: 0;
        }
        .toolbar form {
          display: flex;
          gap: 6px;
          margin: 0;
        }
        .message {
          font-size: clamp(0.76rem, 1.8vh, 0.92rem);
          font-weight: 600;
          padding: 6px 10px;
          border-radius: 12px;
          background: var(--surface);
          border: 1px solid rgba(122, 62, 29, 0.12);
          display: flex;
          align-items: center;
          overflow: hidden;
          line-height: 1.18;
          min-width: 0;
        }
        .message span {
          display: -webkit-box;
          -webkit-line-clamp: 2;
          -webkit-box-orient: vertical;
          overflow: hidden;
        }
        .toolbar button {
          border: 1px solid rgba(0, 0, 0, 0.06);
          border-radius: 999px;
          padding: 7px 11px;
          background: var(--accent);
          color: white;
          font: inherit;
          font-size: clamp(0.76rem, 1.8vh, 0.92rem);
          font-weight: 600;
          cursor: pointer;
          box-shadow: 0 6px 14px rgba(122, 62, 29, 0.18);
          transition: transform 120ms ease, background 120ms ease;
          white-space: nowrap;
        }
        .toolbar button:hover {
          background: var(--accent-dark);
          transform: translateY(-1px);
        }
        .toolbar button[disabled] {
          background: rgba(122, 62, 29, 0.38);
          cursor: not-allowed;
          transform: none;
          box-shadow: none;
        }
        .game-area {
          display: grid;
          grid-template-columns: minmax(0, 1fr) minmax(190px, 240px);
          gap: clamp(8px, 1.6vw, 16px);
          align-items: start;
          min-height: 0;
          flex: 1 1 auto;
        }
        .board {
          display: grid;
          grid-template-columns: repeat({{ board_size }}, minmax(0, 1fr));
          gap: 0;
          width: min(100%, calc(100dvh - 112px), 760px);
          aspect-ratio: 1;
          margin: 0 auto;
          flex: 0 1 auto;
          box-sizing: border-box;
          position: relative;
          overflow: hidden;
          border-radius: 18px;
          background:
            linear-gradient(180deg, rgba(255, 241, 214, 0.45), rgba(151, 105, 47, 0.12)),
            var(--board);
          box-shadow:
            inset 0 1px 0 rgba(255, 244, 220, 0.45),
            inset 0 -10px 18px rgba(122, 76, 27, 0.12),
            0 16px 34px rgba(76, 49, 24, 0.16);
        }
        .board::before {
          --grid-step: calc(100% / ({{ board_size }} - 1));
          content: "";
          position: absolute;
          inset: calc(50% / {{ board_size }});
          background:
            repeating-linear-gradient(
              to right,
              transparent 0 calc(var(--grid-step) - 1px),
              var(--board-line) calc(var(--grid-step) - 1px) calc(var(--grid-step) + 0.5px),
              transparent calc(var(--grid-step) + 0.5px) var(--grid-step)
            ),
            repeating-linear-gradient(
              to bottom,
              transparent 0 calc(var(--grid-step) - 1px),
              var(--board-line) calc(var(--grid-step) - 1px) calc(var(--grid-step) + 0.5px),
              transparent calc(var(--grid-step) + 0.5px) var(--grid-step)
            );
          background-size: 100% 100%;
          background-repeat: no-repeat;
          pointer-events: none;
          z-index: 0;
        }
        .board::after {
          content: "";
          position: absolute;
          inset: calc(50% / {{ board_size }});
          border: 1.5px solid var(--board-line);
          pointer-events: none;
          z-index: 0;
        }
        .cell-form {
          margin: 0;
          position: relative;
          z-index: 1;
        }
        .cell {
          aspect-ratio: 1;
          width: 100%;
          appearance: none;
          -webkit-appearance: none;
          display: block;
          border: none;
          border-radius: 0;
          background: transparent;
          padding: 0;
          font-size: 0;
          color: transparent;
          position: relative;
          overflow: hidden;
        }
        .stone {
          position: absolute;
          left: 50%;
          top: 50%;
          width: 72%;
          height: 72%;
          border-radius: 50%;
          transform: translate(-50%, -50%) scale(0);
          transition: transform 120ms ease, box-shadow 120ms ease, background 120ms ease;
          z-index: 1;
        }
        .cell.empty:hover:not([disabled]) .stone {
          transform: translate(-50%, -50%) scale(0.34);
          background: rgba(255, 248, 235, 0.45);
          box-shadow: inset 0 0 0 1px rgba(90, 58, 25, 0.18);
        }
        .cell.black {
          cursor: default;
        }
        .cell.black .stone {
          transform: translate(-50%, -50%) scale(1);
          background: radial-gradient(circle at 30% 30%, #55504a, var(--stone-black) 58%, #090909 100%);
          box-shadow:
            inset -5px -6px 10px rgba(255, 255, 255, 0.05),
            0 7px 12px rgba(15, 14, 13, 0.26);
        }
        .cell.white {
          cursor: default;
        }
        .cell.white .stone {
          transform: translate(-50%, -50%) scale(1);
          background: radial-gradient(circle at 30% 30%, #ffffff, #f6eddc 68%, #d8ccb8 100%);
          box-shadow:
            inset -4px -5px 8px rgba(110, 92, 65, 0.12),
            0 7px 12px rgba(95, 78, 51, 0.16);
        }
        .cell.empty {
          cursor: pointer;
        }
        .cell.empty[disabled] {
          cursor: not-allowed;
        }
        .hint {
          position: absolute;
          left: 50%;
          top: 50%;
          transform: translate(-50%, -50%);
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
          width: 76%;
          height: 76%;
          border-radius: 50%;
          background: rgba(122, 62, 29, 0.82);
          color: #fff8ef;
          box-shadow: 0 8px 18px rgba(80, 42, 18, 0.24);
          z-index: 2;
          pointer-events: none;
        }
        .hint-rank {
          font-size: clamp(0.54rem, 1.55vh, 0.76rem);
          font-weight: 700;
          letter-spacing: 0.06em;
          line-height: 1;
        }
        .hint-prob {
          margin-top: 2px;
          font-size: clamp(0.62rem, 1.75vh, 0.88rem);
          font-weight: 700;
          line-height: 1;
        }
        .hint-count {
          margin-top: 2px;
          font-size: clamp(0.52rem, 1.42vh, 0.72rem);
          font-weight: 700;
          line-height: 1;
          opacity: 0.92;
        }
        .board-value {
          position: absolute;
          right: 8px;
          top: 8px;
          z-index: 3;
          padding: 5px 8px;
          border-radius: 999px;
          background: rgba(255, 252, 243, 0.92);
          border: 1px solid rgba(122, 62, 29, 0.12);
          color: var(--text);
          font-size: clamp(0.62rem, 1.6vh, 0.8rem);
          font-weight: 700;
          pointer-events: none;
        }
        .mcts-panel {
          align-self: stretch;
          min-height: 0;
          padding: 12px;
          border-radius: 14px;
          background: var(--surface);
          border: 1px solid rgba(122, 62, 29, 0.12);
          box-sizing: border-box;
          overflow: hidden;
        }
        .mcts-title {
          display: flex;
          justify-content: space-between;
          gap: 8px;
          margin-bottom: 10px;
          font-size: clamp(0.84rem, 1.9vh, 0.96rem);
          font-weight: 700;
          color: rgba(36, 23, 13, 0.72);
        }
        .mcts-list {
          display: grid;
          gap: 8px;
        }
        .mcts-move {
          border-radius: 12px;
          overflow: hidden;
          background: rgba(255, 249, 236, 0.9);
          border: 1px solid rgba(122, 62, 29, 0.12);
        }
        .mcts-head {
          display: flex;
          justify-content: space-between;
          gap: 8px;
          padding: 7px 9px;
          background: rgba(122, 62, 29, 0.08);
          font-size: clamp(0.82rem, 1.9vh, 0.94rem);
          font-weight: 700;
        }
        .mcts-grid {
          display: grid;
          grid-template-columns: auto minmax(0, 1fr);
          gap: 0;
          font-size: clamp(0.78rem, 1.75vh, 0.9rem);
          line-height: 1.16;
          font-variant-numeric: tabular-nums;
        }
        .mcts-label {
          padding: 7px 0 7px 9px;
          color: rgba(36, 23, 13, 0.64);
          border-top: 1px solid rgba(122, 62, 29, 0.08);
        }
        .mcts-value {
          padding: 7px 9px 7px 0;
          text-align: right;
          font-weight: 700;
          overflow: hidden;
          text-overflow: ellipsis;
          border-top: 1px solid rgba(122, 62, 29, 0.08);
        }
        @media (max-width: 640px) {
          .status-area {
            grid-template-columns: 1fr;
          }
          main {
            padding: 6px;
          }
          .panel {
            padding: 7px;
            border-radius: 16px;
          }
          .game-area {
            grid-template-columns: 1fr;
            gap: 6px;
          }
          .board {
            width: min(100%, calc(100dvh - 122px));
          }
          .mcts-panel {
            display: none;
          }
        }
        @media (max-width: 860px) {
          .game-area {
            grid-template-columns: 1fr;
          }
          .mcts-panel {
            display: none;
          }
          .board {
            width: min(100%, calc(100dvh - 122px));
          }
        }
      </style>
    </head>
    <body>
      <main>
        <section class="panel">
          <div class="status-area">
            <div class="toolbar">
              <form method="post" action="{{ url_for('new_game') }}">
                <button type="submit" name="player_color" value="0">Play Black</button>
                <button type="submit" name="player_color" value="1">Play White</button>
              </form>
              <form method="post" action="{{ url_for('undo_move') }}">
                <button type="submit" {% if not can_undo %}disabled{% endif %}>
                  Undo{% if undo_count %} {{ undo_count }}{% endif %}
                </button>
              </form>
            </div>
            <div class="message"><span>{{ message }}</span></div>
          </div>
          <div class="game-area">
            <div class="board">
              {% if analysis %}
                <div class="board-value">Value {{ "%.3f"|format(analysis.value) }}</div>
              {% endif %}
              {% for row_idx in range(board_size) %}
                {% for col_idx in range(board_size) %}
                  {% set cell = board[row_idx][col_idx] %}
                  {% set action = row_idx * board_size + col_idx %}
                  {% set hint = analysis_by_action.get(action) %}
                  <form class="cell-form" method="post" action="{{ url_for('board_click') }}">
                    <input type="hidden" name="action" value="{{ action }}">
                    <button
                      class="cell {% if cell == 'B' %}black{% elif cell == 'W' %}white{% else %}empty{% endif %}"
                      type="submit"
                      {% if game_over or (next_turn == player_color and cell) %}disabled{% endif %}
                    >
                      <span class="stone"></span>
                      {% if hint and not cell %}
                        <span class="hint">
                          <span class="hint-rank">#{{ hint.rank }}</span>
                          <span class="hint-prob">{{ hint.prob_pct }}%</span>
                          {% if hint.mcts_count is not none %}
                            <span class="hint-count">N={{ hint.mcts_count }}</span>
                          {% endif %}
                        </span>
                      {% endif %}
                    </button>
                  </form>
                {% endfor %}
              {% endfor %}
            </div>
            <aside class="mcts-panel" aria-label="MCTS root statistics">
              {% if analysis and analysis.moves and analysis.moves[0].q is not none %}
                <div class="mcts-title">
                  <span>Top MCTS moves</span>
                  <span>N={{ analysis.moves | sum(attribute='mcts_count') }}</span>
                </div>
                <div class="mcts-list">
                  {% for move in analysis.moves %}
                    <div class="mcts-move">
                      <div class="mcts-head">
                        <span>#{{ loop.index }}</span>
                        <span>N={{ move.mcts_count }}</span>
                      </div>
                      <div class="mcts-grid">
                        <span class="mcts-label">Q</span>
                        <span class="mcts-value">{{ "%.4f"|format(move.q) }}</span>
                        <span class="mcts-label">Exploration</span>
                        <span class="mcts-value">{{ "%.4f"|format(move.prior_boost) }}</span>
                        <span class="mcts-label">P</span>
                        <span class="mcts-value">{{ "%.4f"|format(move.p) }}</span>
                        <span class="mcts-label">Node Novelty</span>
                        <span class="mcts-value">{{ "%.4f"|format(move.exploration) }}</span>
                      </div>
                    </div>
                  {% endfor %}
                </div>
              {% endif %}
            </aside>
          </div>
        </section>
      </main>
    </body>
    </html>
    """

    @app.post("/new-game")
    def new_game():
        player_color = parse_int_form_value("player_color")
        if player_color not in {0, 1}:
            return redirect(url_for("index"))
        app.config["GAME_STATE"] = initialize_game_state(
            app.config["POLICY"],
            app.config["MCTS_POLICY"],
            app.config["DEVICE"],
            player_color,
        )
        return redirect(url_for("index"))

    @app.post("/undo")
    def undo_move():
        game_state = app.config["GAME_STATE"]
        if not can_undo_player_move(game_state):
            return redirect(url_for("index"))

        undo_stack = list(game_state.get("undo_stack") or [])
        undo_state = undo_stack.pop()
        app.config["GAME_STATE"] = restore_undo_snapshot(
            undo_state,
            undo_stack,
            f"Move undone. {len(undo_stack)} undo{'s' if len(undo_stack) != 1 else ''} left.",
        )
        return redirect(url_for("index"))

    @app.post("/move")
    def board_click():
        game_state = app.config["GAME_STATE"]
        if game_state["game_over"]:
            return redirect(url_for("index"))

        action = parse_int_form_value("action")
        if action is None or not 0 <= action < BOARD_SIZE**2:
            game_state["message"] = "Invalid move. Pick a board square."
            return redirect(url_for("index"))

        board = game_state["board"]
        player_color = game_state["player_color"]
        policy_color = 1 - player_color

        if game_state["next_turn"] == policy_color:
            return play_policy_move()
        if game_state["next_turn"] != player_color:
            return redirect(url_for("index"))

        undo_stack = push_undo_snapshot(game_state)
        try:
            board = step(board, action, whose_turn=player_color)
        except ValueError:
            game_state["message"] = "Illegal move. Pick an empty square."
            return redirect(url_for("index"))

        outcome = evaluate_outcome(board, last_player=player_color, action=action)
        if outcome is not None:
            app.config["GAME_STATE"] = make_game_state(
                board=board,
                message=outcome,
                game_over=True,
                player_color=player_color,
                next_turn=None,
                last_action=action,
                undo_stack=undo_stack,
            )
            return redirect(url_for("index"))

        mcts = game_state.get("mcts")
        if USE_MCTS_UI:
            if mcts is None:
                mcts = create_mcts(app.config["MCTS_POLICY"], board, policy_color, action)
            else:
                mcts.advance_root(action)

        analysis_moves, analysis_value, selected_action = analyze_policy_state(
            app.config["POLICY"],
            board,
            policy_color,
            top_k=3,
            last_action=action,
            use_mcts=USE_MCTS_UI,
            mcts=mcts,
            mcts_policy=app.config["MCTS_POLICY"],
        )
        app.config["GAME_STATE"] = make_game_state(
            board=board,
            message="Your move is placed. The policy's top moves are shown on the board.",
            game_over=False,
            player_color=player_color,
            next_turn=policy_color,
            last_action=action,
            analysis={
                "moves": analysis_moves,
                "value": analysis_value,
                "selected_action": selected_action,
            },
            mcts=mcts,
            undo_stack=undo_stack,
        )
        return redirect(url_for("index"))

    def play_policy_move():
        game_state = app.config["GAME_STATE"]
        if game_state["game_over"] or game_state["player_color"] is None:
            return redirect(url_for("index"))

        board = game_state["board"]
        player_color = game_state["player_color"]
        policy_color = 1 - player_color
        last_action = game_state["last_action"]
        if game_state["next_turn"] != policy_color:
            return redirect(url_for("index"))

        analysis = game_state["analysis"]
        mcts = game_state.get("mcts")
        policy_action = None
        if USE_MCTS_UI and analysis is not None:
            policy_action = analysis.get("selected_action")
        if policy_action is None:
            if USE_MCTS_UI:
                if mcts is None:
                    mcts = create_mcts(app.config["MCTS_POLICY"], board, policy_color, last_action)
                policy_action, _, _ = mcts.select_action()
            else:
                policy_action = select_policy_action(app.config["POLICY"], board, policy_color)
        if policy_action is None:
            app.config["GAME_STATE"] = make_game_state(
                board=board,
                message="Draw.",
                game_over=True,
                player_color=player_color,
                next_turn=None,
                last_action=last_action,
                undo_stack=game_state.get("undo_stack") or [],
            )
            return redirect(url_for("index"))

        board = step(board, policy_action, whose_turn=policy_color)
        outcome = evaluate_outcome(board, last_player=policy_color, action=policy_action)
        if USE_MCTS_UI and mcts is None and outcome is None:
            mcts = create_mcts(app.config["MCTS_POLICY"], board, player_color, policy_action)
        message = outcome or f"Policy played at row {policy_action // BOARD_SIZE}, col {policy_action % BOARD_SIZE}."
        app.config["GAME_STATE"] = make_game_state(
            board=board,
            message=message,
            game_over=outcome is not None,
            player_color=player_color,
            next_turn=None if outcome is not None else player_color,
            last_action=policy_action,
            mcts=None if outcome is not None else mcts,
            undo_stack=game_state.get("undo_stack") or [],
        )
        return redirect(url_for("index"))

    @app.get("/")
    def index():
        game_state = app.config["GAME_STATE"]
        analysis = game_state["analysis"]
        analysis_by_action = {}
        if analysis is not None:
            for idx, move in enumerate(analysis["moves"], start=1):
                analysis_by_action[move["action"]] = {
                    "rank": idx,
                    "prob_pct": move["prob_pct"],
                    "mcts_count": move["mcts_count"],
                }
        return render_template_string(
            template,
            board=board_to_symbols(game_state["board"]),
            board_size=BOARD_SIZE,
            game_over=game_state["game_over"],
            message=game_state["message"],
            model_path=str(app.config["MODEL_PATH"]),
            player_color=game_state["player_color"],
            policy_color=None if game_state["player_color"] is None else 1 - game_state["player_color"],
            next_turn=game_state["next_turn"],
            analysis=analysis,
            analysis_by_action=analysis_by_action,
            can_undo=can_undo_player_move(game_state),
            undo_count=len(game_state.get("undo_stack") or []),
        )

    return app


def browser_url_for_host(host, port):
    if host in {"0.0.0.0", "::"}:
        browser_host = "127.0.0.1"
    else:
        browser_host = host
    return f"http://{browser_host}:{port}"


def open_browser_later(url, delay=1.0):
    timer = threading.Timer(delay, lambda: webbrowser.open(url))
    timer.daemon = True
    timer.start()


def port_is_available(host, port):
    bind_host = "0.0.0.0" if host == "::" else host
    family = socket.AF_INET6 if ":" in bind_host and bind_host != "0.0.0.0" else socket.AF_INET
    with socket.socket(family, socket.SOCK_STREAM) as sock:
        sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        try:
            sock.bind((bind_host, port))
        except OSError:
            return False
    return True


def choose_port(host, preferred_port, max_tries=20):
    for port in range(preferred_port, preferred_port + max_tries):
        if port_is_available(host, port):
            return port
    raise RuntimeError(f"No available port found in range {preferred_port}-{preferred_port + max_tries - 1}.")


def parse_args():
    parser = argparse.ArgumentParser(description="Play Gomoku against a saved policy in a browser.")
    parser.add_argument("--model-path", type=Path, default=DEFAULT_MODEL_PATH, help="Which saved weights to load.")
    parser.add_argument("--host", default="0.0.0.0", help="Bind address for the server.")
    parser.add_argument("--port", type=int, default=5000, help="Port for the server.")
    parser.add_argument(
        "--no-browser",
        action="store_true",
        help="Do not automatically open the app in the default browser.",
    )
    return parser.parse_args()


def main():
    args = parse_args()

    if not args.model_path.exists():
        raise FileNotFoundError(
            f"No saved weights found at {args.model_path}. Train and save them from gomoku/main.py first."
        )

    app = create_app(model_path=args.model_path)
    chosen_port = choose_port(args.host, args.port)
    if chosen_port != args.port:
        print(f"Port {args.port} is in use. Falling back to {chosen_port}.")
    launch_url = browser_url_for_host(args.host, chosen_port)
    print(f"Launching Gomoku UI at {launch_url}")
    if not args.no_browser:
        open_browser_later(launch_url)
    app.run(host=args.host, port=chosen_port, debug=False)


if __name__ == "__main__":
    main()
