# This file is generated by Codex, since it has no core RL logic inside.

import argparse
from pathlib import Path

import torch
import torch.nn.functional as F
from flask import Flask, redirect, render_template_string, request, url_for

from config import BOARD_SIZE, UI_ITER
from main import PolicyNetwork, check_win_cond, step


DEFAULT_MODEL_PATH = Path(f"final_policy_{UI_ITER}.pt")


def get_device():
    if torch.backends.mps.is_available():
        return torch.device("mps")
    return torch.device("cpu")


def empty_board(device=None):
    if device is None:
        device = get_device()
    return torch.zeros((2, BOARD_SIZE, BOARD_SIZE), dtype=torch.float32, device=device)


def load_policy(path, device=None):
    if device is None:
        device = get_device()
    policy = PolicyNetwork().to(device)
    state_dict = torch.load(Path(path), map_location=device)
    policy.load_state_dict(state_dict)
    policy.eval()
    return policy


def board_to_symbols(state):
    occupied = state[0] + 2 * state[1]
    cells = []
    for row_idx in range(BOARD_SIZE):
        row = []
        for col_idx in range(BOARD_SIZE):
            cell = int(occupied[row_idx][col_idx].item())
            if cell == 1:
                row.append("B")
            elif cell == 2:
                row.append("W")
            else:
                row.append("")
        cells.append(row)
    return cells


def board_is_full(state):
    return bool((state.sum(dim=0) != 0).all().item())


def select_policy_action(policy, state, policy_turn):
    if policy_turn == 0:
        policy_state = state
    else:
        policy_state = torch.stack([state[1], state[0]])

    with torch.no_grad():
        action_logits = policy(policy_state.unsqueeze(0)).squeeze(0)
        occupied_spaces = state.sum(dim=0)
        legal_mask = (occupied_spaces == 0).flatten()
        if not legal_mask.any():
            return None
        masked_logits = action_logits.masked_fill(~legal_mask, float("-inf"))
        action_probs = F.softmax(masked_logits, dim=-1)
        action_dist = torch.distributions.Categorical(probs=action_probs)
        return int(action_dist.sample().item())


def evaluate_outcome(state, last_player, action):
    winner = check_win_cond(state, last_player, action)
    if winner == 0:
        return "Black wins."
    if winner == 1:
        return "White wins."
    if board_is_full(state):
        return "Draw."
    return None


def create_app(model_path=DEFAULT_MODEL_PATH):
    app = Flask(__name__)
    app.config["MODEL_PATH"] = Path(model_path)
    app.config["DEVICE"] = get_device()
    app.config["POLICY"] = load_policy(app.config["MODEL_PATH"], app.config["DEVICE"])
    app.config["GAME_STATE"] = {
        "board": empty_board(device=app.config["DEVICE"]),
        "message": "New game. You are Black and move first.",
        "game_over": False,
    }

    template = """
    <!doctype html>
    <html lang="en">
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>Gomoku vs Policy</title>
      <style>
        :root {
          color-scheme: light;
          --bg: #efe2c4;
          --bg-deep: #d6b983;
          --panel: rgba(255, 249, 236, 0.76);
          --board: #c89d62;
          --board-line: rgba(70, 45, 20, 0.48);
          --text: #24170d;
          --accent: #7a3e1d;
          --accent-dark: #5d2f17;
          --stone-black: #1f1d1b;
          --stone-white: #fbf7ef;
          --shadow: rgba(64, 34, 15, 0.18);
        }
        body {
          margin: 0;
          min-height: 100vh;
          font-family: Georgia, "Times New Roman", serif;
          background:
            radial-gradient(circle at top, rgba(255, 252, 243, 0.95), transparent 32%),
            linear-gradient(180deg, #f8edd5 0%, var(--bg) 42%, var(--bg-deep) 100%);
          color: var(--text);
        }
        main {
          max-width: 860px;
          margin: 0 auto;
          min-height: 100dvh;
          box-sizing: border-box;
          display: flex;
          flex-direction: column;
          justify-content: center;
          padding: 16px 16px 18px;
        }
        h1 {
          margin: 0 0 4px;
          font-size: clamp(1.85rem, 3.6vw, 2.8rem);
          letter-spacing: 0.02em;
        }
        p {
          margin: 0 0 10px;
          line-height: 1.35;
          max-width: none;
          font-size: 0.92rem;
          color: rgba(36, 23, 13, 0.78);
        }
        .panel {
          background: var(--panel);
          border: 1px solid rgba(102, 66, 32, 0.18);
          border-radius: 28px;
          padding: 16px;
          box-shadow: 0 24px 54px var(--shadow);
          backdrop-filter: blur(10px);
        }
        .toolbar {
          display: flex;
          flex-wrap: wrap;
          justify-content: space-between;
          align-items: center;
          gap: 10px;
          margin-bottom: 12px;
        }
        .message {
          font-size: 0.96rem;
          font-weight: 600;
          padding: 8px 12px;
          border-radius: 999px;
          background: rgba(255, 252, 243, 0.85);
          border: 1px solid rgba(122, 62, 29, 0.12);
        }
        .toolbar button {
          border: 1px solid rgba(0, 0, 0, 0.06);
          border-radius: 999px;
          padding: 9px 15px;
          background: var(--accent);
          color: white;
          font: inherit;
          font-weight: 600;
          cursor: pointer;
          box-shadow: 0 10px 20px rgba(122, 62, 29, 0.18);
          transition: transform 120ms ease, background 120ms ease;
        }
        .toolbar button:hover {
          background: var(--accent-dark);
          transform: translateY(-1px);
        }
        .board {
          display: grid;
          grid-template-columns: repeat({{ board_size }}, minmax(0, 1fr));
          gap: 0;
          width: min(100%, min(74vh, 74vw));
          aspect-ratio: 1;
          margin: 0 auto;
          box-sizing: border-box;
          position: relative;
          overflow: hidden;
          border-radius: 26px;
          background:
            linear-gradient(180deg, rgba(255, 241, 214, 0.45), rgba(151, 105, 47, 0.12)),
            var(--board);
          box-shadow:
            inset 0 1px 0 rgba(255, 244, 220, 0.45),
            inset 0 -10px 18px rgba(122, 76, 27, 0.12),
            0 16px 34px rgba(76, 49, 24, 0.16);
        }
        .board::before {
          --grid-step: calc(100% / ({{ board_size }} - 1));
          content: "";
          position: absolute;
          inset: calc(50% / {{ board_size }});
          background:
            repeating-linear-gradient(
              to right,
              transparent 0 calc(var(--grid-step) - 1px),
              var(--board-line) calc(var(--grid-step) - 1px) calc(var(--grid-step) + 0.5px),
              transparent calc(var(--grid-step) + 0.5px) var(--grid-step)
            ),
            repeating-linear-gradient(
              to bottom,
              transparent 0 calc(var(--grid-step) - 1px),
              var(--board-line) calc(var(--grid-step) - 1px) calc(var(--grid-step) + 0.5px),
              transparent calc(var(--grid-step) + 0.5px) var(--grid-step)
            );
          background-size: 100% 100%;
          background-repeat: no-repeat;
          pointer-events: none;
          z-index: 0;
        }
        .board::after {
          content: "";
          position: absolute;
          inset: calc(50% / {{ board_size }});
          border: 1.5px solid var(--board-line);
          pointer-events: none;
          z-index: 0;
        }
        .cell-form {
          margin: 0;
          position: relative;
          z-index: 1;
        }
        .cell {
          aspect-ratio: 1;
          width: 100%;
          appearance: none;
          -webkit-appearance: none;
          display: block;
          border: none;
          border-radius: 0;
          background: transparent;
          padding: 0;
          font-size: 0;
          color: transparent;
          position: relative;
        }
        .stone {
          position: absolute;
          left: 50%;
          top: 50%;
          width: 72%;
          height: 72%;
          border-radius: 50%;
          transform: translate(-50%, -50%) scale(0);
          transition: transform 120ms ease, box-shadow 120ms ease, background 120ms ease;
          z-index: 1;
        }
        .cell.empty:hover:not([disabled]) .stone {
          transform: translate(-50%, -50%) scale(0.34);
          background: rgba(255, 248, 235, 0.45);
          box-shadow: inset 0 0 0 1px rgba(90, 58, 25, 0.18);
        }
        .cell.black {
          cursor: default;
        }
        .cell.black .stone {
          transform: translate(-50%, -50%) scale(1);
          background: radial-gradient(circle at 30% 30%, #55504a, var(--stone-black) 58%, #090909 100%);
          box-shadow:
            inset -5px -6px 10px rgba(255, 255, 255, 0.05),
            0 7px 12px rgba(15, 14, 13, 0.26);
        }
        .cell.white {
          cursor: default;
        }
        .cell.white .stone {
          transform: translate(-50%, -50%) scale(1);
          background: radial-gradient(circle at 30% 30%, #ffffff, #f6eddc 68%, #d8ccb8 100%);
          box-shadow:
            inset -4px -5px 8px rgba(110, 92, 65, 0.12),
            0 7px 12px rgba(95, 78, 51, 0.16);
        }
        .cell.empty {
          cursor: pointer;
        }
        .cell.empty[disabled] {
          cursor: not-allowed;
        }
        @media (max-width: 640px) {
          main {
            min-height: auto;
            padding: 10px 10px 14px;
          }
          .panel {
            padding: 10px;
            border-radius: 22px;
          }
          .board {
            width: min(100%, calc(100vh - 150px));
          }
          .message {
            font-size: 0.9rem;
          }
        }
      </style>
    </head>
    <body>
      <main>
        <h1>Gomoku vs Policy</h1>
        <p>The saved weights are loaded from <code>{{ model_path }}</code>. You play Black; the policy plays White.</p>
        <section class="panel">
          <div class="toolbar">
            <div class="message">{{ message }}</div>
            <form method="post" action="{{ url_for('new_game') }}">
              <button type="submit">New Game</button>
            </form>
          </div>
          <div class="board">
            {% for row_idx in range(board_size) %}
              {% for col_idx in range(board_size) %}
                {% set cell = board[row_idx][col_idx] %}
                {% set action = row_idx * board_size + col_idx %}
                <form class="cell-form" method="post" action="{{ url_for('play_move') }}">
                  <input type="hidden" name="action" value="{{ action }}">
                  <button
                    class="cell {% if cell == 'B' %}black{% elif cell == 'W' %}white{% else %}empty{% endif %}"
                    type="submit"
                    {% if game_over or cell %}disabled{% endif %}
                  >
                    <span class="stone"></span>
                  </button>
                </form>
              {% endfor %}
            {% endfor %}
          </div>
        </section>
      </main>
    </body>
    </html>
    """

    @app.post("/new-game")
    def new_game():
        app.config["GAME_STATE"] = {
            "board": empty_board(device=app.config["DEVICE"]),
            "message": "New game. You are Black and move first.",
            "game_over": False,
        }
        return redirect(url_for("index"))

    @app.post("/move")
    def play_move():
        game_state = app.config["GAME_STATE"]
        if game_state["game_over"]:
            return redirect(url_for("index"))

        action = int(request.form["action"])
        board = game_state["board"]

        try:
            board = step(board, action, whose_turn=0)
        except ValueError:
            game_state["message"] = "Illegal move. Pick an empty square."
            return redirect(url_for("index"))

        outcome = evaluate_outcome(board, last_player=0, action=action)
        if outcome is not None:
            app.config["GAME_STATE"] = {
                "board": board,
                "message": outcome,
                "game_over": True,
            }
            return redirect(url_for("index"))

        policy_action = select_policy_action(app.config["POLICY"], board, policy_turn=1)
        if policy_action is None:
            app.config["GAME_STATE"] = {
                "board": board,
                "message": "Draw.",
                "game_over": True,
            }
            return redirect(url_for("index"))

        board = step(board, policy_action, whose_turn=1)
        outcome = evaluate_outcome(board, last_player=1, action=policy_action)
        message = outcome or f"Policy played at row {policy_action // BOARD_SIZE}, col {policy_action % BOARD_SIZE}."
        app.config["GAME_STATE"] = {
            "board": board,
            "message": message,
            "game_over": outcome is not None,
        }
        return redirect(url_for("index"))

    @app.get("/")
    def index():
        game_state = app.config["GAME_STATE"]
        return render_template_string(
            template,
            board=board_to_symbols(game_state["board"]),
            board_size=BOARD_SIZE,
            game_over=game_state["game_over"],
            message=game_state["message"],
            model_path=str(app.config["MODEL_PATH"]),
        )

    return app


def parse_args():
    parser = argparse.ArgumentParser(description="Play Gomoku against a saved policy in a browser.")
    parser.add_argument("--model-path", type=Path, default=DEFAULT_MODEL_PATH, help="Which saved weights to load.")
    parser.add_argument("--host", default="127.0.0.1", help="Bind address for the server.")
    parser.add_argument("--port", type=int, default=5000, help="Port for the server.")
    return parser.parse_args()


def main():
    args = parse_args()

    if not args.model_path.exists():
        raise FileNotFoundError(
            f"No saved weights found at {args.model_path}. Train and save them from gomoku/main.py first."
        )

    app = create_app(model_path=args.model_path)
    app.run(host=args.host, port=args.port, debug=False)


if __name__ == "__main__":
    main()
