# This file is generated by Codex, since it has no core RL logic inside.

import argparse
from pathlib import Path
import socket
import threading
import webbrowser

import torch
import torch.nn.functional as F
from flask import Flask, redirect, render_template_string, request, url_for

from config import BOARD_SIZE, UI_ITER, CURRENT_MODELS_DIR
from model import PolicyNetwork
from utils import check_win_cond, step


DEFAULT_MODEL_PATH = CURRENT_MODELS_DIR / f"final_policy_{UI_ITER}.pt"


def get_device():
    if torch.backends.mps.is_available():
        return torch.device("mps")
    return torch.device("cpu")


def empty_board(device=None):
    if device is None:
        device = get_device()
    return torch.zeros((2, BOARD_SIZE, BOARD_SIZE), dtype=torch.float32, device=device)


def load_policy(path, device=None):
    if device is None:
        device = get_device()
    policy = PolicyNetwork().to(device)
    checkpoint = torch.load(Path(path), map_location=device)
    state_dict = checkpoint["model"] if "model" in checkpoint else checkpoint
    policy.load_state_dict(state_dict)
    policy.eval()
    return policy


def board_to_symbols(state):
    occupied = state[0] + 2 * state[1]
    cells = []
    for row_idx in range(BOARD_SIZE):
        row = []
        for col_idx in range(BOARD_SIZE):
            cell = int(occupied[row_idx][col_idx].item())
            if cell == 1:
                row.append("B")
            elif cell == 2:
                row.append("W")
            else:
                row.append("")
        cells.append(row)
    return cells


def board_is_full(state):
    return bool((state.sum(dim=0) != 0).all().item())


def select_policy_action(policy, state, policy_turn):
    if policy_turn == 0:
        policy_state = state
    else:
        policy_state = torch.stack([state[1], state[0]])

    with torch.no_grad():
        action_logits, value = policy(policy_state.unsqueeze(0))
        action_logits = action_logits.squeeze(0)
        occupied_spaces = state.sum(dim=0)
        legal_mask = (occupied_spaces == 0).flatten()
        if not legal_mask.any():
            return None
        masked_logits = action_logits.masked_fill(~legal_mask, float("-inf"))
        action_probs = F.softmax(masked_logits, dim=-1)
        action_dist = torch.distributions.Categorical(probs=action_probs)
        return int(action_dist.sample().item())


def analyze_policy_state(policy, state, policy_turn, top_k=3):
    if policy_turn == 0:
        policy_state = state
    else:
        policy_state = torch.stack([state[1], state[0]])

    with torch.no_grad():
        action_logits, value = policy(policy_state.unsqueeze(0))
        action_logits = action_logits.squeeze(0)
        value = float(value.squeeze().item())
        occupied_spaces = state.sum(dim=0)
        legal_mask = (occupied_spaces == 0).flatten()
        if not legal_mask.any():
            return [], value

        masked_logits = action_logits.masked_fill(~legal_mask, float("-inf"))
        action_probs = F.softmax(masked_logits, dim=-1)
        top_probs, top_actions = torch.topk(action_probs, k=min(top_k, int(legal_mask.sum().item())))

    ranked_moves = []
    for action, prob in zip(top_actions.tolist(), top_probs.tolist()):
        ranked_moves.append({
            "action": action,
            "row": action // BOARD_SIZE,
            "col": action % BOARD_SIZE,
            "prob_pct": round(prob * 100),
        })
    return ranked_moves, value


def evaluate_outcome(state, last_player, action):
    winner = check_win_cond(state, last_player, action)
    if winner == 0:
        return "Black wins."
    if winner == 1:
        return "White wins."
    if board_is_full(state):
        return "Draw."
    return None


def initialize_game_state(policy, device, player_color):
    board = empty_board(device=device)
    if player_color == 0:
        return {
            "board": board,
            "message": "New game. You are Black and move first.",
            "game_over": False,
            "player_color": 0,
            "next_turn": 0,
            "analysis": None,
        }

    moves, value = analyze_policy_state(policy, board, policy_turn=0, top_k=3)
    if not moves:
        return {
            "board": board,
            "message": "Draw.",
            "game_over": True,
            "player_color": 1,
            "next_turn": None,
            "analysis": None,
        }

    return {
        "board": board,
        "message": "New game. You are White. The policy is about to open as Black.",
        "game_over": False,
        "player_color": 1,
        "next_turn": 0,
        "analysis": {
            "moves": moves,
            "value": value,
        },
    }


def create_app(model_path=DEFAULT_MODEL_PATH):
    app = Flask(__name__)
    app.config["MODEL_PATH"] = Path(model_path)
    app.config["DEVICE"] = get_device()
    app.config["POLICY"] = load_policy(app.config["MODEL_PATH"], app.config["DEVICE"])
    app.config["GAME_STATE"] = {
        "board": empty_board(device=app.config["DEVICE"]),
        "message": "Choose whether to play Black or White to start a new game.",
        "game_over": True,
        "player_color": None,
        "next_turn": None,
        "analysis": None,
    }

    template = """
    <!doctype html>
    <html lang="en">
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>Gomoku vs Policy</title>
      <style>
        :root {
          color-scheme: light;
          --bg: #efe2c4;
          --bg-deep: #d6b983;
          --panel: rgba(255, 249, 236, 0.76);
          --board: #c89d62;
          --board-line: rgba(70, 45, 20, 0.48);
          --text: #24170d;
          --accent: #7a3e1d;
          --accent-dark: #5d2f17;
          --stone-black: #1f1d1b;
          --stone-white: #fbf7ef;
          --shadow: rgba(64, 34, 15, 0.18);
        }
        body {
          margin: 0;
          min-height: 100vh;
          font-family: Georgia, "Times New Roman", serif;
          background:
            radial-gradient(circle at top, rgba(255, 252, 243, 0.95), transparent 32%),
            linear-gradient(180deg, #f8edd5 0%, var(--bg) 42%, var(--bg-deep) 100%);
          color: var(--text);
        }
        main {
          max-width: 860px;
          margin: 0 auto;
          min-height: 100dvh;
          box-sizing: border-box;
          display: flex;
          flex-direction: column;
          justify-content: flex-start;
          padding: 16px 16px 18px;
        }
        p {
          margin: 0 0 10px;
          line-height: 1.35;
          max-width: none;
          font-size: 0.92rem;
          color: rgba(36, 23, 13, 0.78);
        }
        .panel {
          background: var(--panel);
          border: 1px solid rgba(102, 66, 32, 0.18);
          border-radius: 28px;
          padding: 16px;
          box-shadow: 0 24px 54px var(--shadow);
          backdrop-filter: blur(10px);
          display: flex;
          flex-direction: column;
          align-items: stretch;
        }
        .status-area {
          display: grid;
          grid-template-rows: 52px 56px;
          gap: 12px;
          margin-bottom: 12px;
          flex: 0 0 auto;
        }
        .toolbar {
          display: flex;
          flex-wrap: nowrap;
          justify-content: flex-start;
          align-items: center;
          gap: 10px;
          min-height: 52px;
        }
        .message {
          font-size: 0.96rem;
          font-weight: 600;
          padding: 8px 12px;
          border-radius: 999px;
          background: rgba(255, 252, 243, 0.85);
          border: 1px solid rgba(122, 62, 29, 0.12);
          min-height: 22px;
          display: flex;
          align-items: center;
          overflow: hidden;
        }
        .toolbar button {
          border: 1px solid rgba(0, 0, 0, 0.06);
          border-radius: 999px;
          padding: 9px 15px;
          background: var(--accent);
          color: white;
          font: inherit;
          font-weight: 600;
          cursor: pointer;
          box-shadow: 0 10px 20px rgba(122, 62, 29, 0.18);
          transition: transform 120ms ease, background 120ms ease;
        }
        .toolbar button:hover {
          background: var(--accent-dark);
          transform: translateY(-1px);
        }
        .message-row {
          min-height: 56px;
          display: flex;
          align-items: center;
        }
        .board {
          display: grid;
          grid-template-columns: repeat({{ board_size }}, minmax(0, 1fr));
          gap: 0;
          width: min(100%, min(74vh, 74vw));
          aspect-ratio: 1;
          margin: 0 auto;
          flex: 0 0 auto;
          box-sizing: border-box;
          position: relative;
          overflow: hidden;
          border-radius: 26px;
          background:
            linear-gradient(180deg, rgba(255, 241, 214, 0.45), rgba(151, 105, 47, 0.12)),
            var(--board);
          box-shadow:
            inset 0 1px 0 rgba(255, 244, 220, 0.45),
            inset 0 -10px 18px rgba(122, 76, 27, 0.12),
            0 16px 34px rgba(76, 49, 24, 0.16);
        }
        .board::before {
          --grid-step: calc(100% / ({{ board_size }} - 1));
          content: "";
          position: absolute;
          inset: calc(50% / {{ board_size }});
          background:
            repeating-linear-gradient(
              to right,
              transparent 0 calc(var(--grid-step) - 1px),
              var(--board-line) calc(var(--grid-step) - 1px) calc(var(--grid-step) + 0.5px),
              transparent calc(var(--grid-step) + 0.5px) var(--grid-step)
            ),
            repeating-linear-gradient(
              to bottom,
              transparent 0 calc(var(--grid-step) - 1px),
              var(--board-line) calc(var(--grid-step) - 1px) calc(var(--grid-step) + 0.5px),
              transparent calc(var(--grid-step) + 0.5px) var(--grid-step)
            );
          background-size: 100% 100%;
          background-repeat: no-repeat;
          pointer-events: none;
          z-index: 0;
        }
        .board::after {
          content: "";
          position: absolute;
          inset: calc(50% / {{ board_size }});
          border: 1.5px solid var(--board-line);
          pointer-events: none;
          z-index: 0;
        }
        .cell-form {
          margin: 0;
          position: relative;
          z-index: 1;
        }
        .cell {
          aspect-ratio: 1;
          width: 100%;
          appearance: none;
          -webkit-appearance: none;
          display: block;
          border: none;
          border-radius: 0;
          background: transparent;
          padding: 0;
          font-size: 0;
          color: transparent;
          position: relative;
          overflow: hidden;
        }
        .stone {
          position: absolute;
          left: 50%;
          top: 50%;
          width: 72%;
          height: 72%;
          border-radius: 50%;
          transform: translate(-50%, -50%) scale(0);
          transition: transform 120ms ease, box-shadow 120ms ease, background 120ms ease;
          z-index: 1;
        }
        .cell.empty:hover:not([disabled]) .stone {
          transform: translate(-50%, -50%) scale(0.34);
          background: rgba(255, 248, 235, 0.45);
          box-shadow: inset 0 0 0 1px rgba(90, 58, 25, 0.18);
        }
        .cell.black {
          cursor: default;
        }
        .cell.black .stone {
          transform: translate(-50%, -50%) scale(1);
          background: radial-gradient(circle at 30% 30%, #55504a, var(--stone-black) 58%, #090909 100%);
          box-shadow:
            inset -5px -6px 10px rgba(255, 255, 255, 0.05),
            0 7px 12px rgba(15, 14, 13, 0.26);
        }
        .cell.white {
          cursor: default;
        }
        .cell.white .stone {
          transform: translate(-50%, -50%) scale(1);
          background: radial-gradient(circle at 30% 30%, #ffffff, #f6eddc 68%, #d8ccb8 100%);
          box-shadow:
            inset -4px -5px 8px rgba(110, 92, 65, 0.12),
            0 7px 12px rgba(95, 78, 51, 0.16);
        }
        .cell.empty {
          cursor: pointer;
        }
        .cell.empty[disabled] {
          cursor: not-allowed;
        }
        .hint {
          position: absolute;
          left: 50%;
          top: 50%;
          transform: translate(-50%, -50%);
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
          width: 76%;
          height: 76%;
          border-radius: 50%;
          background: rgba(122, 62, 29, 0.82);
          color: #fff8ef;
          box-shadow: 0 8px 18px rgba(80, 42, 18, 0.24);
          z-index: 2;
          pointer-events: none;
        }
        .hint-rank {
          font-size: 0.68rem;
          font-weight: 700;
          letter-spacing: 0.06em;
          line-height: 1;
        }
        .hint-prob {
          margin-top: 3px;
          font-size: 0.78rem;
          font-weight: 700;
          line-height: 1;
        }
        .board-value {
          position: absolute;
          right: 12px;
          top: 12px;
          z-index: 3;
          padding: 6px 10px;
          border-radius: 999px;
          background: rgba(255, 252, 243, 0.92);
          border: 1px solid rgba(122, 62, 29, 0.12);
          color: var(--text);
          font-size: 0.8rem;
          font-weight: 700;
          pointer-events: none;
        }
        @media (max-width: 640px) {
          .status-area {
            grid-template-rows: 88px 64px;
          }
          .toolbar {
            flex-wrap: wrap;
          }
          main {
            padding: 10px 10px 14px;
          }
          .panel {
            padding: 10px;
            border-radius: 22px;
          }
          .board {
            width: min(100%, calc(100vh - 150px));
          }
          .message {
            font-size: 0.9rem;
          }
        }
      </style>
    </head>
    <body>
      <main>
        <p>The saved weights are loaded from <code>{{ model_path }}</code>. Choose Black or White for each new game.</p>
        <section class="panel">
          <div class="status-area">
            <div class="toolbar">
              <form method="post" action="{{ url_for('new_game') }}">
                <button type="submit" name="player_color" value="0">Play Black</button>
                <button type="submit" name="player_color" value="1">Play White</button>
              </form>
            </div>
            <div class="message-row">
              <div class="message">{{ message }}</div>
            </div>
          </div>
          <div class="board">
            {% if analysis %}
              <div class="board-value">Value {{ "%.3f"|format(analysis.value) }}</div>
            {% endif %}
            {% for row_idx in range(board_size) %}
              {% for col_idx in range(board_size) %}
                {% set cell = board[row_idx][col_idx] %}
                {% set action = row_idx * board_size + col_idx %}
                {% set hint = analysis_by_action.get(action) %}
                <form class="cell-form" method="post" action="{{ url_for('board_click') }}">
                  <input type="hidden" name="action" value="{{ action }}">
                  <button
                    class="cell {% if cell == 'B' %}black{% elif cell == 'W' %}white{% else %}empty{% endif %}"
                    type="submit"
                    {% if game_over or (next_turn == player_color and cell) %}disabled{% endif %}
                  >
                    <span class="stone"></span>
                    {% if hint and not cell %}
                      <span class="hint">
                        <span class="hint-rank">#{{ hint.rank }}</span>
                        <span class="hint-prob">{{ hint.prob_pct }}%</span>
                      </span>
                    {% endif %}
                  </button>
                </form>
              {% endfor %}
            {% endfor %}
          </div>
        </section>
      </main>
    </body>
    </html>
    """

    @app.post("/new-game")
    def new_game():
        player_color = int(request.form["player_color"])
        app.config["GAME_STATE"] = initialize_game_state(
            app.config["POLICY"],
            app.config["DEVICE"],
            player_color,
        )
        return redirect(url_for("index"))

    @app.post("/move")
    def board_click():
        game_state = app.config["GAME_STATE"]
        if game_state["game_over"]:
            return redirect(url_for("index"))

        action = int(request.form["action"])
        board = game_state["board"]
        player_color = game_state["player_color"]
        policy_color = 1 - player_color

        if game_state["next_turn"] == policy_color:
            return play_policy_move()
        if game_state["next_turn"] != player_color:
            return redirect(url_for("index"))

        try:
            board = step(board, action, whose_turn=player_color)
        except ValueError:
            game_state["message"] = "Illegal move. Pick an empty square."
            return redirect(url_for("index"))

        outcome = evaluate_outcome(board, last_player=player_color, action=action)
        if outcome is not None:
            app.config["GAME_STATE"] = {
                "board": board,
                "message": outcome,
                "game_over": True,
                "player_color": player_color,
                "next_turn": None,
                "analysis": None,
            }
            return redirect(url_for("index"))

        analysis_moves, analysis_value = analyze_policy_state(
            app.config["POLICY"],
            board,
            policy_color,
            top_k=3,
        )
        app.config["GAME_STATE"] = {
            "board": board,
            "message": "Your move is placed. The policy's top moves are shown on the board.",
            "game_over": False,
            "player_color": player_color,
            "next_turn": policy_color,
            "analysis": {
                "moves": analysis_moves,
                "value": analysis_value,
            },
        }
        return redirect(url_for("index"))

    def play_policy_move():
        game_state = app.config["GAME_STATE"]
        if game_state["game_over"] or game_state["player_color"] is None:
            return redirect(url_for("index"))

        board = game_state["board"]
        player_color = game_state["player_color"]
        policy_color = 1 - player_color
        if game_state["next_turn"] != policy_color:
            return redirect(url_for("index"))

        policy_action = select_policy_action(app.config["POLICY"], board, policy_turn=policy_color)
        if policy_action is None:
            app.config["GAME_STATE"] = {
                "board": board,
                "message": "Draw.",
                "game_over": True,
                "player_color": player_color,
                "next_turn": None,
                "analysis": None,
            }
            return redirect(url_for("index"))

        board = step(board, policy_action, whose_turn=policy_color)
        outcome = evaluate_outcome(board, last_player=policy_color, action=policy_action)
        message = outcome or f"Policy played at row {policy_action // BOARD_SIZE}, col {policy_action % BOARD_SIZE}."
        app.config["GAME_STATE"] = {
            "board": board,
            "message": message,
            "game_over": outcome is not None,
            "player_color": player_color,
            "next_turn": None if outcome is not None else player_color,
            "analysis": None,
        }
        return redirect(url_for("index"))

    @app.get("/")
    def index():
        game_state = app.config["GAME_STATE"]
        analysis = game_state["analysis"]
        analysis_by_action = {}
        if analysis is not None:
            for idx, move in enumerate(analysis["moves"], start=1):
                analysis_by_action[move["action"]] = {
                    "rank": idx,
                    "prob_pct": move["prob_pct"],
                }
        return render_template_string(
            template,
            board=board_to_symbols(game_state["board"]),
            board_size=BOARD_SIZE,
            game_over=game_state["game_over"],
            message=game_state["message"],
            model_path=str(app.config["MODEL_PATH"]),
            player_color=game_state["player_color"],
            policy_color=None if game_state["player_color"] is None else 1 - game_state["player_color"],
            next_turn=game_state["next_turn"],
            analysis=analysis,
            analysis_by_action=analysis_by_action,
        )

    return app


def browser_url_for_host(host, port):
    if host in {"0.0.0.0", "::"}:
        browser_host = "127.0.0.1"
    else:
        browser_host = host
    return f"http://{browser_host}:{port}"


def open_browser_later(url, delay=1.0):
    timer = threading.Timer(delay, lambda: webbrowser.open(url))
    timer.daemon = True
    timer.start()


def port_is_available(host, port):
    bind_host = "0.0.0.0" if host == "::" else host
    family = socket.AF_INET6 if ":" in bind_host and bind_host != "0.0.0.0" else socket.AF_INET
    with socket.socket(family, socket.SOCK_STREAM) as sock:
        sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        try:
            sock.bind((bind_host, port))
        except OSError:
            return False
    return True


def choose_port(host, preferred_port, max_tries=20):
    for port in range(preferred_port, preferred_port + max_tries):
        if port_is_available(host, port):
            return port
    raise RuntimeError(f"No available port found in range {preferred_port}-{preferred_port + max_tries - 1}.")


def parse_args():
    parser = argparse.ArgumentParser(description="Play Gomoku against a saved policy in a browser.")
    parser.add_argument("--model-path", type=Path, default=DEFAULT_MODEL_PATH, help="Which saved weights to load.")
    parser.add_argument("--host", default="0.0.0.0", help="Bind address for the server.")
    parser.add_argument("--port", type=int, default=5000, help="Port for the server.")
    parser.add_argument(
        "--no-browser",
        action="store_true",
        help="Do not automatically open the app in the default browser.",
    )
    return parser.parse_args()


def main():
    args = parse_args()

    if not args.model_path.exists():
        raise FileNotFoundError(
            f"No saved weights found at {args.model_path}. Train and save them from gomoku/main.py first."
        )

    app = create_app(model_path=args.model_path)
    chosen_port = choose_port(args.host, args.port)
    if chosen_port != args.port:
        print(f"Port {args.port} is in use. Falling back to {chosen_port}.")
    launch_url = browser_url_for_host(args.host, chosen_port)
    print(f"Launching Gomoku UI at {launch_url}")
    if not args.no_browser:
        open_browser_later(launch_url)
    app.run(host=args.host, port=chosen_port, debug=False)


if __name__ == "__main__":
    main()
